"""create core tables

Revision ID: 5a0f65ab3d09
Revises: 
Create Date: 2026-09-06 23:23:17.591569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '5a0f65ab3d09'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditevent_incident_id'), 'auditevent', ['incident_id'], unique=False)
    op.create_index(op.f('ix_auditevent_tenant_id'), 'auditevent', ['tenant_id'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('incident',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_scenario_key'), 'incident', ['scenario_key'], unique=False)
    op.create_index(op.f('ix_incident_status'), 'incident', ['status'], unique=False)
    op.create_index(op.f('ix_incident_tenant_id'), 'incident', ['tenant_id'], unique=False)
    op.create_table('actionproposal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('risk_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rollback_plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actionproposal_idempotency_key'), 'actionproposal', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_actionproposal_incident_id'), 'actionproposal', ['incident_id'], unique=False)
    op.create_index(op.f('ix_actionproposal_payload_hash'), 'actionproposal', ['payload_hash'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('citation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_citation_id'), 'evidence', ['citation_id'], unique=False)
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_table('hypothesis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('cause', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('support_ids', sa.JSON(), nullable=True),
    sa.Column('contradict_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_incident_id'), 'hypothesis', ['incident_id'], unique=False)
    op.create_table('approval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('proposal_id', sa.Uuid(), nullable=False),
    sa.Column('payload_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['actionproposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_proposal_id'), 'approval', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_proposal_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_hypothesis_incident_id'), table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_citation_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_actionproposal_payload_hash'), table_name='actionproposal')
    op.drop_index(op.f('ix_actionproposal_incident_id'), table_name='actionproposal')
    op.drop_index(op.f('ix_actionproposal_idempotency_key'), table_name='actionproposal')
    op.drop_table('actionproposal')
    op.drop_index(op.f('ix_incident_tenant_id'), table_name='incident')
    op.drop_index(op.f('ix_incident_status'), table_name='incident')
    op.drop_index(op.f('ix_incident_scenario_key'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_auditevent_tenant_id'), table_name='auditevent')
    op.drop_index(op.f('ix_auditevent_incident_id'), table_name='auditevent')
    op.drop_table('auditevent')
    # ### end Alembic commands ###
